version: "3.5"
services:
  postgres:
    image: postgres:latest
    container_name: l0_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"]
  nats:
    image: nats:2.9.14
    container_name: l0_nats
    ports:
      - "4222:4222"
    command: "-js"