version: "3.5"
services:
  postgres:
    image: postgres:latest
    container_name: l0_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=l0
    command: ["postgres", "-c", "log_statement=all"]
  nats:
    image: nats:2.9.14
    container_name: l0_nats
    ports:
      - "8222:8222"
    command: "-js"